services:
  postgres:
    image: postgres
    container_name: carrentPostgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carrent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - carrent_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: carrentPgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: abdessamadaitbella98@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8088:80"
    depends_on:
      - postgres
    networks:
      - carrent_network

  frontend:
    build:
      context: ./front_end  # Le chemin vers ton dossier front-end
    container_name: carrent_frontend
    restart: always
    ports:
      - "3000:3000"  # Si tu utilises React, c'est généralement sur le port 3000
    volumes:
      - ./front_end:/app  # Monter le dossier front-end pour recompiler à la volée
    networks:
      - carrent_network
    depends_on:
      - php  # Le front-end peut dépendre du back-end si nécessaire


  php:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: carrent_app
    restart: always 
    volumes:
      - ./back_end:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - carrent_network

volumes:
  postgres_data2:
  
networks:
  carrent_network:
